#!/bin/bash
# Copyright (C) 2020 by NavInfo Europe B.V. The Netherlands - All rights reserved
# Information classification: Confidential
# This content is protected by international copyright laws.
# Reproduction and distribution is prohibited without written permission.

# Exit on errors and undefined variables
set -euo pipefail

# Specify package name, version, source, and release
PKG_NAME="libpdal-dev"
PKG_VERSION="2.0.1"
PKG_SOURCE="https://github.com/PDAL/PDAL.git"
PKG_RELEASE="1" # Indicates the version of the generated package

# Install package specific dependencies
apt-get update
apt-get install --no-install-recommends --assume-yes \
    libgeotiff-dev \
    libgdal-dev

# Clone repository
git clone --branch "${PKG_VERSION}" "${PKG_SOURCE}" "${PKG_NAME}"

# Build package
cd ${PKG_NAME}
mkdir build
cd build
cmake   -DCMAKE_BUILD_TYPE=Release \
        -DWITH_TESTS=OFF \
    ..
make -j $(nproc)

# Create Debian package
echo "NavInfo compiled package ${PKG_NAME}" > description-pak
checkinstall \
    --maintainer="IT NavInfo" \
    --pkggroup="navinfo" \
    --pkgname="navinfo-${PKG_NAME}" \
    --pkgversion=${PKG_VERSION} \
    --pkgrelease=${PKG_RELEASE} \
    --pkgsource=${PKG_SOURCE} \
    --arch=${PKG_ARCH} \
    --provides="navinfo-${PKG_NAME}" \
    --requires="libgeotiff-dev, \
                libgdal-dev"
