// This is a modified version of the original HADMapBin.idl from Autoware.
// The original is licensed under the Apache License, Version 2.0. For more information
// see the LICENSE file in the repository root
//
// The changes made in this file, of which a summary is listed below, are copyrighted:
//
// Copyright (C) 2021 by NavInfo Europe B.V. The Netherlands - All rights reserved
// Information classification: Confidential
// This content is protected by international copyright laws.
// Reproduction and distribution is prohibited without written permission.
//
// List of changes:
// * Renamed autoware_auto_msgs to aiim_autoware_msgs

#include "std_msgs/msg/Header.idl"

module aiim_autoware_msgs {
  module msg {
    module HADMapBin_Constants {
      const uint8 MAP_FORMAT_LANELET2 = 0;
    };
    @verbatim(language = "comment", text =
      "HADMap contents in binary blob format")
    struct HADMapBin
    {
      std_msgs::msg::Header header;
      @verbatim(language = "comment", text =
        "HADMap format identifier, allows supporting multiple map formats")
      uint8 map_format;

      @verbatim(language = "comment", text =
        "Version of map format. Keep as empty string if unnecssary")
      @default(value = "")
      string format_version;

      @verbatim(language = "comment", text =
        "Version of map. Keep as empty empty if unnecessary")
      @default(value = "")
      string map_version;

      @verbatim(language = "comment", text =
        "Binary map data")
      sequence < uint8 > data;
    };
  };
};
