/**:
  ros__parameters:
    vehicle:
      # wheel_radius: 0.37 # Measured from SVL
      # wheel_width: 0.27 # Measured from SVL
      # wheel_base: 2.734 # Measured from SVL
      # wheel_tread: 1.571 # Measured from SVL
      # overhang_front: 1.033 # Measured from SVL
      # overhang_rear: 1.021 # Measured from SVL
      # overhang_left: 0.3135 # Measured from SVL
      # overhang_right: 0.3135 # Measured from SVL
      # vehicle_height: 1.662 # Measured from SVL
      # cg_to_rear: 1.367 # Assuming it is in middle of front and rear axle centers
      # tire_cornering_stiffness_front: 0.1 # Taken from AVP demo params, can't verify
      # tire_cornering_stiffness_rear: 0.1 # Taken from AVP demo params, can't verify
      # mass_vehicle: 2120.0 # Measured from SVL
      # inertia_yaw_kg_m2: 12.0  # Taken from AVP demo params, can't verify
      # maximum_turning_angle_rad: 0.53
      
      wheel_radius: 0.31725 # based on a 195/65R15 
      # diameter(mm) = ((195*65) / 100)*2 + 15*25.4
      # https://www.wheel-size.com/size/toyota/prius-prime/2018/ 
      # https://tiresize.com/tiresizes/255-70R18.htm 
      # https://www.randywisechryslerdodgejeepram.com/used-Flint-2018-Toyota-Tundra-Base-5TFUW5F1XJX679247
      
      wheel_width: 0.195 # based on a 195/65R15 

      wheel_base: 2.701 # https://www.edmunds.com/toyota/prius-prime/2018/features-specs/
      wheel_tread: 1.571 # Measured from SVL
      
      overhang_front: 0.97536 
      overhang_rear: 0.97028 
      # https://www.toyota.com/priusprime/ebrochure/ 
      overhang_left: 0.3135 # Measured from SVL
      overhang_right: 0.3135 # Measured from SVL

      vehicle_height: 1.47 # https://www.edmunds.com/toyota/prius-prime/2018/features-specs/

      cg_to_rear: 1.367 # Assuming it is in middle of front and rear axle centers
      tire_cornering_stiffness_front: 0.1 # Taken from AVP demo params, can't verify
      tire_cornering_stiffness_rear: 0.1 # Taken from AVP demo params, can't verify
      
      mass_vehicle: 1775.0 # https://www.auto123.com/en/new-cars/technical-specs/toyota/prius/2018/prime/base/#suspension
      
      inertia_yaw_kg_m2: 12.0  # Taken from AVP demo params, can't verify
      maximum_turning_angle_rad: 0.53 # 10.2-meter turning circle diameter 


