#!/bin/bash
# Copyright (C) 2021 by NavInfo Europe B.V. The Netherlands - All rights reserved
# Information classification: Confidential
# This content is protected by international copyright laws.
# Reproduction and distribution is prohibited without written permission.

# Exit on errors and undefined variables
set -euo pipefail

# Specify package name, version, source, and release
PKG_NAME="libopencv-dev-server-cuda"
PKG_VERSION="4.5.0"
PKG_SOURCE_1="https://github.com/opencv/opencv/archive/${PKG_VERSION}.tar.gz"
PKG_SOURCE_2="https://github.com/opencv/opencv_contrib/archive/${PKG_VERSION}.tar.gz"
PKG_RELEASE="1" # Indicates the version of the generated package

# Install package specific dependencies
apt-get update
apt-get install --no-install-recommends --assume-yes \
    libtbb-dev \
    libjpeg-dev \
    libpng-dev \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \
    libswscale-dev \
    libavresample-dev \
    libatlas-base-dev \
    python3-dev \
    python3-numpy \
    libeigen3-dev

# Download and extract package source
mkdir sources
wget -qO- ${PKG_SOURCE_1} | tar -xzf - -C sources
wget -qO- ${PKG_SOURCE_2} | tar -xzf - -C sources

# Build package
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release \
      -D CUDA_ARCH_BIN="5.2 6.1 7.0 7.5" \
      -D CUDA_ARCH_PTX="5.2 6.1 7.0 7.5" \
      -D WITH_CUBLAS=ON \
      -D WITH_CUDA=ON \
      -D WITH_CUFFT=ON \
      -D WITH_EIGEN=ON \
      -D WITH_GTK=ON \
      -D WITH_JPEG=ON \
      -D WITH_TBB=ON \
      -D WITH_QT=OFF \
      -D WITH_GTK_2_X=OFF \
      -D WITH_FFMPEG=ON \
      -D BUILD_opencv_cudacodec=OFF \
      -D OPENCV_EXTRA_MODULES_PATH=../sources/opencv_contrib-${PKG_VERSION}/modules \
      ../sources/opencv-${PKG_VERSION}
make -j $(nproc)

# Create Debian package
echo "NavInfo compiled package ${PKG_NAME}" > description-pak
checkinstall \
    --maintainer="IT NavInfo" \
    --pkggroup="navinfo" \
    --pkgname="navinfo-${PKG_NAME}" \
    --pkgversion=${PKG_VERSION} \
    --pkgrelease=${PKG_RELEASE} \
    --pkgsource=../sources \
    --arch=${PKG_ARCH} \
    --provides="navinfo-${PKG_NAME}" \
    --conflicts="navinfo-libopencv-dev-server, \
                 navinfo-libopencv-dev-desktop, \
                 navinfo-libopencv-dev-desktop-cuda" \
    --requires="cuda-libraries-dev-11-2, \
                libtbb-dev, \
                libjpeg-dev, \
                libpng-dev, \
                libavcodec-dev, \
                libavformat-dev,\
                libavutil-dev, \
                libswscale-dev, \
                libavresample-dev, \
                libatlas-base-dev, \
                python3-dev, \
                python3-numpy, \
                libeigen3-dev"
