# params/lanelet2_map_publisher.param.yaml
---

/**:
   ros__parameters:
     # map_osm_file: "/home/alireza/map_conversion/myMaps/tue_with_lanelet_edited_Mahmoud.osm" #Delete later, I was trying to see if open drive works
     # map_osm_file: "/home/omax/AIIM/navigation_box/src/lanelet2_map_provider/data/autonomoustuff_parking_lot.osm"
     # The earth-map transform is given by the point cloud map, but when the osm file is projected
     # into the map frame, they might not match exactly. These parameters allow specifying a small
     # correction to the position of the map frame origin for the purpose of this projection. 
     # Added as part of issue #847. The values are in degrees.
     #origin_offset_lat: -5.239983224214484e-06
     #origin_offset_lon: 4.5845488187978845e-06
     latitude: 51.442352316374894
     longitude: 4.438876794395926
     elevation: 16.0
     origin_offset_lat: 0.0
     origin_offset_lon: 0.0
