#!/bin/bash
# Copyright (C) 2020 by NavInfo Europe B.V. The Netherlands - All rights reserved
# Information classification: Confidential
# This content is protected by international copyright laws.
# Reproduction and distribution is prohibited without written permission.

# Exit on errors and undefined variables
set -euo pipefail

# Specify package name, version, source, and release
PKG_NAME="libnanoflann-dev"
PKG_VERSION="1.3.1"
PKG_SOURCE="https://github.com/jlblancoc/nanoflann.git"
PKG_RELEASE="2" # Indicates the version of the generated package

# Install package specific dependencies
apt-get update
apt-get install --no-install-recommends --assume-yes \
    libeigen3-dev

# Clone repository
git clone ${PKG_SOURCE} ${PKG_NAME}

# Build package
cd ${PKG_NAME}
git checkout "v${PKG_VERSION}"
mkdir build
cd build
cmake -D BUILD_EXAMPLES=OFF \
      -D BUILD_TESTS=OFF \
      ..

# Create Debian package
echo "NavInfo compiled package ${PKG_NAME}" > description-pak
checkinstall \
    --maintainer="IT NavInfo" \
    --pkggroup="navinfo" \
    --pkgname="navinfo-${PKG_NAME}" \
    --pkgversion=${PKG_VERSION} \
    --pkgrelease=${PKG_RELEASE} \
    --pkgsource=${PKG_SOURCE} \
    --arch=${PKG_ARCH} \
    --provides="navinfo-${PKG_NAME}" \
    --requires="libeigen3-dev"
