#!/bin/bash
# Copyright (C) 2020 by NavInfo Europe B.V. The Netherlands - All rights reserved
# Information classification: Confidential
# This content is protected by international copyright laws.
# Reproduction and distribution is prohibited without written permission.

# Exit on errors and undefined variables
set -euo pipefail

# Specify package name, version, source, and release
PKG_NAME="liblas-dev"
PKG_VERSION="1.8.1-patched"
PKG_SOURCE="https://github.com/libLAS/libLAS.git"
PKG_RELEASE="3" # Indicates the version of the generated package

# Install package specific dependencies
apt-get update
apt-get install --no-install-recommends --assume-yes \
    libboost-all-dev \
    libgeotiff-dev

# Clone repository
git clone ${PKG_SOURCE} ${PKG_NAME}

# Build package
cd ${PKG_NAME}
# liblas tag 1.8.1 is lastest, and library is now 'in maintenance mode', so use a fixed commit on the master branch
git checkout -b patch dfe16f1d363ea90b639f5600d076da7f7efa8bfe
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release \
      ..
make -j $(nproc)

# Create Debian package
echo "NavInfo compiled package ${PKG_NAME}" > description-pak
checkinstall \
    --maintainer="IT NavInfo" \
    --pkggroup="navinfo" \
    --pkgname="navinfo-${PKG_NAME}" \
    --pkgversion=${PKG_VERSION} \
    --pkgrelease=${PKG_RELEASE} \
    --pkgsource=${PKG_SOURCE} \
    --arch=${PKG_ARCH} \
    --provides="navinfo-${PKG_NAME}" \
    --requires="libboost-all-dev, \
                libgeotiff-dev"
